//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terrasoft.Tools.SvnUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terrasoft.Tools.SvnUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER
        ///SUCCESS.
        /// </summary>
        public static string BackgrountTextTop {
            get {
                return ResourceManager.GetString("BackgrountTextTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url к Branches.
        /// </summary>
        public static string BranchesFeatureUrl {
            get {
                return ResourceManager.GetString("BranchesFeatureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url в которой базируются все фитчи.
        /// </summary>
        public static string BranchesFeatureUrlDescription {
            get {
                return ResourceManager.GetString("BranchesFeatureUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url к фитче.
        /// </summary>
        public static string BranchFeatureUrl {
            get {
                return ResourceManager.GetString("BranchFeatureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url в которой расположена фитча.
        /// </summary>
        public static string BranchFeatureUrlDescription {
            get {
                return ResourceManager.GetString("BranchFeatureUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url к PackageStore.
        /// </summary>
        public static string BranchReleaseUrl {
            get {
                return ResourceManager.GetString("BranchReleaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url в которой базируется релиз.
        /// </summary>
        public static string BranchReleaseUrlDescription {
            get {
                return ResourceManager.GetString("BranchReleaseUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коммитить.
        /// </summary>
        public static string CommitIfNoError {
            get {
                return ResourceManager.GetString("CommitIfNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматически фиксировать изменения, в случае отсутсвия ошибок.
        /// </summary>
        public static string CommitIfNoErrorDescription {
            get {
                return ResourceManager.GetString("CommitIfNoErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать фичу.
        /// </summary>
        public static string CreateFeature {
            get {
                return ResourceManager.GetString("CreateFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название фитчи.
        /// </summary>
        public static string FeatureName {
            get {
                return ResourceManager.GetString("FeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название фитчи, фигурирует в названии ветки.
        /// </summary>
        public static string FeatureNameDescription {
            get {
                return ResourceManager.GetString("FeatureNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не может быть пустым.
        /// </summary>
        public static string IsEmpryPropertyValueMessage {
            get {
                return ResourceManager.GetString("IsEmpryPropertyValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатель.
        /// </summary>
        public static string Maintainer {
            get {
                return ResourceManager.GetString("Maintainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатель, фигурирует в названии ветки.
        /// </summary>
        public static string MaintainerDescription {
            get {
                return ResourceManager.GetString("MaintainerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить лог.
        /// </summary>
        public static string SaveLog {
            get {
                return ResourceManager.GetString("SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль Svn.
        /// </summary>
        public static string SvnPassword {
            get {
                return ResourceManager.GetString("SvnPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль пользователя SVN.
        /// </summary>
        public static string SvnPasswordDescription {
            get {
                return ResourceManager.GetString("SvnPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин Svn.
        /// </summary>
        public static string SvnUser {
            get {
                return ResourceManager.GetString("SvnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя SVN.
        /// </summary>
        public static string SvnUserDescription {
            get {
                return ResourceManager.GetString("SvnUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к рабочей копии.
        /// </summary>
        public static string WorkingCopyPath {
            get {
                return ResourceManager.GetString("WorkingCopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к локальной рабочей копии.
        /// </summary>
        public static string WorkingCopyPathDescription {
            get {
                return ResourceManager.GetString("WorkingCopyPathDescription", resourceCulture);
            }
        }
    }
}
