//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terrasoft.Tools.SvnUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terrasoft.Tools.SvnUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER
        ///SUCCESS.
        /// </summary>
        public static string BackgrountTextTop {
            get {
                return ResourceManager.GetString("BackgrountTextTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к бэкапу.
        /// </summary>
        public static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url к Branches.
        /// </summary>
        public static string BranchesFeatureUrl {
            get {
                return ResourceManager.GetString("BranchesFeatureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url в которой базируются все фитчи.
        /// </summary>
        public static string BranchesFeatureUrlDescription {
            get {
                return ResourceManager.GetString("BranchesFeatureUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url к фитче.
        /// </summary>
        public static string BranchFeatureUrl {
            get {
                return ResourceManager.GetString("BranchFeatureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url в которой расположена фитча.
        /// </summary>
        public static string BranchFeatureUrlDescription {
            get {
                return ResourceManager.GetString("BranchFeatureUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url к PackageStore.
        /// </summary>
        public static string BranchReleaseUrl {
            get {
                return ResourceManager.GetString("BranchReleaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url в которой базируется релиз.
        /// </summary>
        public static string BranchReleaseUrlDescription {
            get {
                return ResourceManager.GetString("BranchReleaseUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть ветку.
        /// </summary>
        public static string CloseFeature {
            get {
                return ResourceManager.GetString("CloseFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коммитить.
        /// </summary>
        public static string CommitIfNoError {
            get {
                return ResourceManager.GetString("CommitIfNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматически фиксировать изменения, в случае отсутсвия ошибок.
        /// </summary>
        public static string CommitIfNoErrorDescription {
            get {
                return ResourceManager.GetString("CommitIfNoErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать фичу.
        /// </summary>
        public static string CreateFeature {
            get {
                return ResourceManager.GetString("CreateFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша версия актуальная.
        /// </summary>
        public static string CurrentVersionIsActual {
            get {
                return ResourceManager.GetString("CurrentVersionIsActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных.
        /// </summary>
        public static string DataBase {
            get {
                return ResourceManager.GetString("DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название бд.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть
        ///приложение.
        /// </summary>
        public static string DeployApp {
            get {
                return ResourceManager.GetString("DeployApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть приложение.
        /// </summary>
        public static string DeployApplication {
            get {
                return ResourceManager.GetString("DeployApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть базу данных.
        /// </summary>
        public static string ExpandDatabase {
            get {
                return ResourceManager.GetString("ExpandDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть сайт.
        /// </summary>
        public static string ExpandSite {
            get {
                return ResourceManager.GetString("ExpandSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название фитчи.
        /// </summary>
        public static string FeatureName {
            get {
                return ResourceManager.GetString("FeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название фитчи, фигурирует в названии ветки.
        /// </summary>
        public static string FeatureNameDescription {
            get {
                return ResourceManager.GetString("FeatureNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить разработку.
        /// </summary>
        public static string FinishFeature {
            get {
                return ResourceManager.GetString("FinishFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исправить ветку.
        /// </summary>
        public static string FixFeature {
            get {
                return ResourceManager.GetString("FixFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите закрыть ветку?.
        /// </summary>
        public static string IfCloseFeatureMessage {
            get {
                return ResourceManager.GetString("IfCloseFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не может быть пустым.
        /// </summary>
        public static string IsEmpryPropertyValueMessage {
            get {
                return ResourceManager.GetString("IsEmpryPropertyValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатель.
        /// </summary>
        public static string Maintainer {
            get {
                return ResourceManager.GetString("Maintainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатель, фигурирует в названии ветки.
        /// </summary>
        public static string MaintainerDescription {
            get {
                return ResourceManager.GetString("MaintainerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsSql.
        /// </summary>
        public static string MsSql {
            get {
                return ResourceManager.GetString("MsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle.
        /// </summary>
        public static string Oracle {
            get {
                return ResourceManager.GetString("Oracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить лог.
        /// </summary>
        public static string SaveLog {
            get {
                return ResourceManager.GetString("SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название сервера.
        /// </summary>
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svn.
        /// </summary>
        public static string SvnBranches {
            get {
                return ResourceManager.GetString("SvnBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция завершена.
        /// </summary>
        public static string SvnOperationComplite {
            get {
                return ResourceManager.GetString("SvnOperationComplite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль Svn.
        /// </summary>
        public static string SvnPassword {
            get {
                return ResourceManager.GetString("SvnPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль пользователя SVN.
        /// </summary>
        public static string SvnPasswordDescription {
            get {
                return ResourceManager.GetString("SvnPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин Svn.
        /// </summary>
        public static string SvnUser {
            get {
                return ResourceManager.GetString("SvnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя SVN.
        /// </summary>
        public static string SvnUserDescription {
            get {
                return ResourceManager.GetString("SvnUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить приложение?.
        /// </summary>
        public static string UpdateAppText {
            get {
                return ResourceManager.GetString("UpdateAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить фичу.
        /// </summary>
        public static string UpdateFeature {
            get {
                return ResourceManager.GetString("UpdateFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин сервера.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль сервера.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к рабочей копии.
        /// </summary>
        public static string WorkingCopyPath {
            get {
                return ResourceManager.GetString("WorkingCopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к локальной рабочей копии.
        /// </summary>
        public static string WorkingCopyPathDescription {
            get {
                return ResourceManager.GetString("WorkingCopyPathDescription", resourceCulture);
            }
        }
    }
}
