//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terrasoft.Tools.SVN.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terrasoft.Tools.SVN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использование:
        ///	Terrasoft.Tools.SVN.exe &lt;команда&gt; [аргументы]
        ///Команды:
        ///	-Operation:		В качестве операции выбрать одну из следующих операций: CreateFeature, UpdateFeature, FinishFeature, CloseFeature, ChangeLanguage
        ///		CreateFeature :	Выделение новой ветки для фитчи на основании родительской
        ///		UpdateFeature :	Обновить ветку фитчи изменениями из родительской ветки
        ///		FinishFeature :	Завершить разработку фитчи, путем реинтеграции ветки фитчи в родительску ветку
        ///		CloseFeature  :	Пометь фитчу как завершенн [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Program_Usage {
            get {
                return ResourceManager.GetString("Program_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реинтеграция базовой ветки в ветку фитчи.
        /// </summary>
        public static string SvnUtils_CommitChanges_Reintegrate_base_branch_to_feature {
            get {
                return ResourceManager.GetString("SvnUtils_CommitChanges_Reintegrate_base_branch_to_feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходные коды не разрешены.
        /// </summary>
        public static string SvnUtils_CommitChanges_Sources_not_resolved {
            get {
                return ResourceManager.GetString("SvnUtils_CommitChanges_Sources_not_resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #0
        ///Создание ветки для фитчи: {0}.
        /// </summary>
        public static string SvnUtils_CopyBaseBranch_Init_Feature {
            get {
                return ResourceManager.GetString("SvnUtils_CopyBaseBranch_Init_Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зафиксировано в ревизии №{0}..
        /// </summary>
        public static string SvnUtils_SvnCommitArgsOnCommitted_Commited_revision {
            get {
                return ResourceManager.GetString("SvnUtils_SvnCommitArgsOnCommitted_Commited_revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элементов для фиксации: {0}.
        /// </summary>
        public static string SvnUtils_SvnCommitArgsOnCommitting_Items_to_commit {
            get {
                return ResourceManager.GetString("SvnUtils_SvnCommitArgsOnCommitting_Items_to_commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие не выбрано!.
        /// </summary>
        public static string SvnUtils_SvnReintegrationMergeArgsOnConflict_Action_Not_Selected {
            get {
                return ResourceManager.GetString("SvnUtils_SvnReintegrationMergeArgsOnConflict_Action_Not_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружен конфликт в файле: {0}.
        /// </summary>
        public static string SvnUtils_SvnReintegrationMergeArgsOnConflict_Conflict_in_file {
            get {
                return ResourceManager.GetString("SvnUtils_SvnReintegrationMergeArgsOnConflict_Conflict_in_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл {0} обновлен до ревизии №{1}.
        /// </summary>
        public static string SvnUtils_SvnUpdateArgsOnNotify_Update_to_revision {
            get {
                return ResourceManager.GetString("SvnUtils_SvnUpdateArgsOnNotify_Update_to_revision", resourceCulture);
            }
        }
    }
}
